#include <iostream>
#include "includes/Course.hpp"
#include "includes/Events.hpp"
#include "includes/Form.hpp"
#include "includes/Person.hpp"
#include "includes/Room.hpp"
#include "includes/forms/CourseFinishedForm.hpp"
#include "includes/forms/NeedCourseCreationForm.hpp"
#include "includes/forms/NeedMoreClassRoomForm.hpp"
#include "includes/forms/SubscriptionToCourseForm.hpp"
#include "includes/persons/Staff.hpp"
#include "includes/persons/Student.hpp"
#include "includes/persons/staffs/Headmaster.hpp"
#include "includes/persons/staffs/Professor.hpp"
#include "includes/persons/staffs/Secretary.hpp"
#include "includes/rooms/Classroom.hpp"
#include "includes/rooms/Courtyard.hpp"
#include "includes/rooms/HeadmasterOffice.hpp"
#include "includes/rooms/SecretarialOffice.hpp"
#include "includes/rooms/StaffRestRoom.hpp"

int	main() {}
